CollectableNames:
  - "strawberry"
  - "key"
Music:
  - Name: "event:/PathofHope/FieldofHopesandDreams"

    Weight: 7
  - Name: "event:/PathofHope/RMX_Field"

    Weight: 7
  - Name: "event:/PathofHope/CSide_RudeBuster"


    Weight: 7
  - Name: "event:/PathofHope/DR_RudeBuster"

    Weight: 7
  - Name: "event:/PathofHope/Bird_Intermission"

    Weight: 7
  - Name: "event:/PathofHope/Lovania_Field"
    Weight: 7
  - Name: "event:/PathofHope/WorldRevolving"
    Weight: 7
  - Name: "event:/PathofHope/MegaloRevolving"
    Weight: 7